name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev \
            gawk git gettext libssl-dev wget zstd

      - name: Download OpenWrt SDK
        run: |
          SDK_URL="https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/openwrt-sdk-qualcommax-ipq807x_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
          wget $SDK_URL
          zstd -d openwrt-sdk-*.tar.zst
          tar -xf openwrt-sdk-*.tar
          rm -rf openwrt-sdk-*.tar
          rm -rf openwrt-sdk-*.tar.zst
          mv openwrt-sdk-* openwrt-sdk

      - name: Prepare Package Source
        run: |
          cd openwrt-sdk/package
          git clone https://github.com/xiaorouji/openwrt-passwall2.git

      - name: Update Feeds
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Package
        run: |
          cd openwrt-sdk
          echo "CONFIG_PACKAGE_luci-app-passwall2=m" > .config
          make defconfig
          make package/luci-app-passwall2/compile V=s

      - name: List Built Files
        run: |
          echo "=== Listing all package directories ==="
          ls -la openwrt-sdk/bin/packages/aarch64_cortex-a53/
          echo "=== Looking for passwall2 files ==="
          find openwrt-sdk/bin/packages/ -name "*passwall2*" -type f

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openwrt-sdk/bin/packages/aarch64_cortex-a53/base/luci-app-passwall2*.apk
            openwrt-sdk/bin/packages/aarch64_cortex-a53/base/luci-i18n-passwall2*.apk
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## LuCI App PassWall2 - Release ${{ github.ref_name }}
            
            ### 安装说明 / Installation
            
            下载 `.apk` 文件，适用于 Qualcomm IPQ8071A 平台设备：
            - 支持 Qualcommax IPQ807x 系列芯片 (如 IPQ8071A)
            - ARM64 架构
            - 基于最新 OpenWrt snapshots 构建
            
            安装命令：
            ```bash
            apk add --allow-untrusted luci-app-passwall2_*.apk
            ```
            
            ### 功能特性 / Features
            - 科学上网工具
            - 支持多种代理协议
            - 现代 LuCI 界面
            - 支持节点订阅和自动更新
            
            ### 依赖要求 / Dependencies
            - xray-core
            - 相关代理工具 (根据配置选择)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}